export const PERSISTENT_LOGIN_LOADING = "PERSISTENT_LOGIN_LOADING";
export const PERSISTENT_LOGIN_SUCCESS = "PERSISTENT_LOGIN_SUCCESS";
export const PERSISTENT_LOGIN_FAIL = "PERSISTENT_LOGIN_FAIL";

export const LOGIN_WITH_USERNAME_LOADING = "LOGIN_WITH_USERNAME_LOADING";
export const LOGIN_WITH_USERNAME_SUCCESS = "LOGIN_WITH_USERNAME_SUCCESS";
export const LOGIN_WITH_USERNAME_FAIL = "LOGIN_WITH_USERNAME_FAIL";

export const REFRESH_ACCESS_TOKEN = "REFRESH_ACCESS_TOKEN";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";